name: mac

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '!bump-version'
      - '!bump_version'
      - '!doc?'
      - '!pod'

jobs:
  perl:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@master
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: curl -sL https://git.io/cpm | perl - install -g --cpanfile=cpanfile.mac --show-build-log-on-failure
      - name: Run benchmarks
        run: perl -Ilib t/run.t